# Generated by Django 3.2.5 on 2021-09-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggstra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggsavailable',
            old_name='gather_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='eggsavailable',
            old_name='gather_notes',
            new_name='notes',
        ),
    ]
